CREATE TABLE FlatImages (
Id INT NOT NULL PRIMARY KEY,
Imagepath NVARCHAR(128) NULL);

CREATE TABLE Users (
Id INT NOT NULL PRIMARY KEY,
Username NVARCHAR(32) NOT NULL,
Password NVARCHAR(32) NOT NULL,
Firstname NVARCHAR(64) NOT NULL,
Lastname NVARCHAR(64) NOT NULL,
Email NVARCHAR(128) NOT NULL,
ProfilePic NVARCHAR(128)  NULL,
IsActive BIT NOT NULL);

CREATE TABLE Flat (
Id INT NOT NULL PRIMARY KEY,
OwnerId INT NOT NULL,
PostCode TINYINT NOT NULL,
Address NVARCHAR(64) NOT NULL,
Title NVARCHAR(32) NOT NULL,
Price REAL NOT NULL,
RoomCount Decimal(2,1) NOT NULL,
MainPic NVARCHAR(128) NULL,
IsActive BIT NOT NULL,
Location NVARCHAR(32) NOT NULL,
CONSTRAINT flat_users FOREIGN KEY (OwnerId) REFERENCES Users(Id) ON DELETE CASCADE);

CREATE TABLE Offer (
Id INT NOT NULL PRIMARY KEY,
RenterId INT NOT NULL,
FlatId INT NOT NULL,
Username NVARCHAR(32) NOT NULL,
CONSTRAINT offer_renter FOREIGN KEY (RenterId) REFERENCES Users(Id) ON DELETE CASCADE,
CONSTRAINT offer_flat FOREIGN KEY (FlatId) REFERENCES Flat(Id)); 